### ISSUE TITLE
[Newbie Question] Is OK to use?

### ISSUE THREAD

**Issue by satoshinotdead** [SimonVerhoek/mixcloudbulkdownloader#2]
Hi Simon! I wonder if I can test your app or I need to take in mind updating the dependancies or tools that needs to be updated (primarly critical and related to security) at first.

I'm totally new on Python but I manage my own Linux servers and I use Docker daily.

Huge thanks for your work,
M.

**Comment by SimonVerhoek** [comment]
Hi M.,

All vulnerabilities indicated by Dependabot have been solved as of v0.1.22.
If you have any questions/feedback, please let me know!
